insert into questions (QuestionID, Title, UserText) values (1, 'Statistician III', 'Face to face bottom-line hub');
insert into questions (QuestionID, Title, UserText) values (2, 'Systems Administrator IV', 'Automated neutral framework');
insert into questions (QuestionID, Title, UserText) values (3, 'VP Accounting', 'Total optimal data-warehouse');
insert into questions (QuestionID, Title, UserText) values (4, 'Quality Control Specialist', 'Proactive interactive framework');
insert into questions (QuestionID, Title, UserText) values (5, 'Information Systems Manager', 'Assimilated exuding task-force');
insert into questions (QuestionID, Title, UserText) values (6, 'Teacher', 'Assimilated dynamic analyzer');
insert into questions (QuestionID, Title, UserText) values (7, 'Librarian', 'Horizontal dedicated frame');
insert into questions (QuestionID, Title, UserText) values (8, 'Tax Accountant', 'Synergized multimedia capability');
insert into questions (QuestionID, Title, UserText) values (9, 'Safety Technician II', 'Configurable analyzing monitoring');
insert into questions (QuestionID, Title, UserText) values (10, 'Analyst Programmer', 'Customizable 24 hour focus group');
insert into questions (QuestionID, Title, UserText) values (11, 'Professor', 'Persistent disintermediate ability');
insert into questions (QuestionID, Title, UserText) values (12, 'Civil Engineer', 'Robust bifurcated alliance');
insert into questions (QuestionID, Title, UserText) values (13, 'Software Consultant', 'Business-focused zero administration system engine');
insert into questions (QuestionID, Title, UserText) values (14, 'Software Engineer III', 'Realigned 6th generation success');
insert into questions (QuestionID, Title, UserText) values (15, 'VP Accounting', 'Organic background synergy');
insert into questions (QuestionID, Title, UserText) values (16, 'VP Quality Control', 'Quality-focused stable ability');
insert into questions (QuestionID, Title, UserText) values (17, 'Statistician II', 'Configurable next generation alliance');
insert into questions (QuestionID, Title, UserText) values (18, 'Mechanical Systems Engineer', 'Digitized asymmetric benchmark');
insert into questions (QuestionID, Title, UserText) values (19, 'Electrical Engineer', 'Robust 6th generation array');
insert into questions (QuestionID, Title, UserText) values (20, 'Senior Sales Associate', 'Cross-group bandwidth-monitored workforce');
